# Generated by Django 3.2.6 on 2021-09-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'amenity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenueAmenity',
            fields=[
                ('venue_amenity_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'venue_amenity',
                'managed': False,
            },
        ),
    ]
