# Generated by Django 3.2.6 on 2021-09-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_amenity_venueamenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayType',
            fields=[
                ('stay_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'stay_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenueStayType',
            fields=[
                ('venue_stay_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'venue_stay_type',
                'managed': False,
            },
        ),
    ]
