# Generated by Django 3.2.6 on 2021-09-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_staytype_venuestaytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('street_two', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('zipcode', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('apt_no', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenuePrice',
            fields=[
                ('venue_price_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('available_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'venue_price',
                'managed': False,
            },
        ),
    ]
