# Generated by Django 3.2.6 on 2021-09-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_location_venueprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueType',
            fields=[
                ('venue_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'venue_type',
                'managed': False,
            },
        ),
    ]
