# Generated by Django 3.2.6 on 2021-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_venuetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueExperiencePrice',
            fields=[
                ('venue_experience_price_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('start_available_datetime', models.DateTimeField()),
                ('end_available_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'venue_experience_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenueStayPrice',
            fields=[
                ('venue_stay_price_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('available_date', models.DateField()),
            ],
            options={
                'db_table': 'venue_stay_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenueTransportationPrice',
            fields=[
                ('venue_transportation_price_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('start_available_datetime', models.DateTimeField()),
                ('end_available_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'venue_transportation_price',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='VenuePrice',
        ),
    ]
