# Generated by Django 3.2.6 on 2021-09-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210927_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('street2', models.CharField(blank=True, max_length=255, null=True)),
                ('apt_no', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('zipcode', models.BigIntegerField()),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
    ]
