# Generated by Django 3.2.6 on 2021-09-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreCategory',
            fields=[
                ('explore_cateogory_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('thumbnail', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'explore_category',
                'managed': False,
            },
        ),
    ]
