# Generated by Django 3.2.6 on 2021-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_explorecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItinerary',
            fields=[
                ('media_itinerary_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'media_itinerary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('media_post_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'media_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaUser',
            fields=[
                ('media_user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'media_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaVenue',
            fields=[
                ('media_venue_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'media_venue',
                'managed': False,
            },
        ),
    ]
