# Generated by Django 3.2.6 on 2021-10-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_mediaitinerary_mediapost_mediauser_mediavenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCategory',
            fields=[
                ('experience_category_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'experience_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenueExperienceCategory',
            fields=[
                ('venue_experience_category_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('experience_category_id', models.BigIntegerField()),
                ('venue_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'venue_experience_category',
                'managed': False,
            },
        ),
    ]
