# Generated by Django 3.2.6 on 2021-10-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_experiencecategory_venueexperiencecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentLike',
            fields=[
                ('post_comment_like_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'post_comment_like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransportationType',
            fields=[
                ('transportation_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transportation_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenueMedia',
            fields=[
                ('venue_media_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'venue_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VenueTransportationType',
            fields=[
                ('venue_transportation_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'venue_transportation_type',
                'managed': False,
            },
        ),
    ]
