# Generated by Django 3.2.6 on 2021-10-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_postcommentlike_transportationtype_venuemedia_venuetransportationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentMention',
            fields=[
                ('post_comment_mention_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'post_comment_mention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostCommentTag',
            fields=[
                ('post_comment_tag_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'post_comment_tag',
                'managed': False,
            },
        ),
    ]
