# Generated by Django 3.2.6 on 2021-10-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_postcommentmention_postcommenttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price_type', models.BigIntegerField()),
                ('venue_price_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'price',
                'managed': False,
            },
        ),
    ]
