# Generated by Django 3.2.6 on 2021-11-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBioMention',
            fields=[
                ('user_bio_mention_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_bio_mention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBioTag',
            fields=[
                ('user_bio_tag_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_bio_tag',
                'managed': False,
            },
        ),
    ]
