# Generated by Django 3.2.6 on 2021-11-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userprofiletaglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
