# Generated by Django 3.2.6 on 2021-11-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211117_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
