# Generated by Django 3.2.6 on 2021-11-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('user_token', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_token',
                'managed': False,
            },
        ),
    ]
