# Generated by Django 3.2.6 on 2021-11-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
