# Generated by Django 3.2.6 on 2021-12-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211118_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('report_post_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reporter_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'report_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportPostReason',
            fields=[
                ('report_post_reason_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'report_post_reason',
                'managed': False,
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
