# Generated by Django 3.2.6 on 2021-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211210_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('report_user_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'report_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportUserReason',
            fields=[
                ('report_user_reason_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'report_user_reason',
                'managed': False,
            },
        ),
    ]
