# Generated by Django 3.2.6 on 2022-01-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_reportuser_reportuserreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDialogs',
            fields=[
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'chat_dialogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('is_removed', models.BooleanField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('read', models.BooleanField()),
            ],
            options={
                'db_table': 'chat_message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatUploadedfile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_uploadedfile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMessageStore',
            fields=[
                ('from_user_id', models.BigIntegerField()),
                ('user_message_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('to_user_id', models.BigIntegerField()),
                ('message', models.CharField(max_length=516)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_message_store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMessageUnsent',
            fields=[
                ('user_message_unsent_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('from_user_id', models.BigIntegerField()),
                ('to_user_id', models.BigIntegerField()),
                ('message', models.CharField(max_length=516)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_message_unsent',
                'managed': False,
            },
        ),
    ]
