# Generated by Django 3.2.6 on 2022-01-14 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_chatdialogs_chatmessage_chatuploadedfile_usermessagestore_usermessageunsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
                ('booking', models.BigIntegerField()),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('payment_option_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('payment_option_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'payment_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentCardOption',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.paymentoption')),
                ('card_number', models.CharField(max_length=255)),
                ('expiry_month', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('expiry_year', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('security_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'payment_card_option',
                'managed': False,
            },
        ),
    ]
